# Generated by Django 3.0.10 on 2020-09-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesadmin',
            old_name='adminipload',
            new_name='adminupload',
        ),
    ]
